---
title: "R Notebook"
output: html_notebook
---

```{r}
library("pryr")
mem_start <- mem_used()
start_time <- Sys.time()
library("tidyverse")
library("e1071")
library("caret")
# Load the required packages
library(ggplot2)
library(reshape2)
library(plotly)
end_time <- Sys.time()
mem_end <- mem_used()
cpu_time <- end_time - start_time
mem_used_chunk <- mem_end - mem_start
cat("CPU time usage of code chunk:",cpu_time,"\n")
cat("Memory usage of code chunk:", mem_used_chunk/1048576, "MB\n")
```


```{r}
mem_start <- mem_used()
start_time <- Sys.time()
car<-read.csv("ca-dealers-used.csv")
end_time <- Sys.time()
mem_end <- mem_used()
cpu_time <- end_time - start_time
mem_used_chunk <- mem_end - mem_start
cat("CPU time usage of code chunk:",cpu_time,"sec\n")
cat("Memory usage of code chunk:", mem_used_chunk/1048576, "MB\n")

```


```{r}
# DATA PREPROCESSING
# 1. FEATURE SELECTION
# 2. REMOVING MISSING AND NAN VALUES
# 3. CONVERTING COLUMNS WITH STRING VALUES INTO CATEGORICAL NUMERIC VALUES

mem_start <- mem_used()
start_time <- Sys.time()

car<-subset(car,select=c(miles, year, make, model,trim,body_type, vehicle_type, drivetrain, transmission, fuel_type,engine_size, city,price))
car_viz<-car
clean_dataset <- function(df) {
  stopifnot(is.data.frame(df))
  df <- na.omit(df) # Drop missing values
  indices_to_keep <- !apply(df, 1, function(row) any(is.na(row) | is.infinite(row) | row == -Inf)) # Check for NaN, Inf, and -Inf
  df <- df[indices_to_keep, , drop = FALSE]
  df <- as.data.frame(lapply(df, as.numeric)) # Convert the remaining columns to numeric type
  return(df)
}

for (col in names(car)) {
  # Check if the column is not a character type
  if (is.character(car[[col]])) {
    # Convert the column to a factor
    car[[col]] <- as.numeric(factor(car[[col]]))
  }
}

car_training<-car[,1:13]

car_training2<-clean_dataset(car_training)


end_time <- Sys.time()
mem_end <- mem_used()
cpu_time <- end_time - start_time
mem_used_chunk <- mem_end - mem_start
cat("CPU time usage of code chunk:",cpu_time,"sec\n")
cat("Memory usage of code chunk:", mem_used_chunk/1048576, "MB\n")
write.csv(car_training2, file = "my_data.csv")
```
```{r}
#BASIC EDA

#Distribution of price variable
hist(car_viz$price,breaks=1000,main="Price",xlab = "Price range",ylab="Count")
hist(car_viz$miles,main="Price",xlab = "Price range",ylab="Count")
```

```{r}
#vizualizing the data for make and count of body type
start_time <- Sys.time()
mem_start <- mem_used()

ggplot(car_viz, aes(x = make)) +
  geom_bar(aes(fill = body_type)) +
  labs(x = "Make", y = "Count of Body Type", title = "Make vs Body Type") +
  theme(plot.title = element_text(size = 18),axis.text.x = element_text(angle = 65,  hjust = 1),legend.key.size = unit(0.2,'cm'),legend.text = element_text(size = 5), legend.title = element_text(size = 5),
        legend.box = "vertical")

end_time <- Sys.time()
mem_end <- mem_used()
cpu_time <- end_time - start_time
mem_used_chunk <- mem_end - mem_start
cat("CPU time usage of code chunk:",cpu_time,"\n")
cat("Memory usage of code chunk:", mem_used_chunk/1048576, "MB\n")

```

```{r}
start_time <- Sys.time()
mem_start <- mem_used()

plotinter<-ggplot(car_viz, aes(x = make)) +
  geom_bar(aes(fill = body_type)) +
  labs(x = "Make", y = "Count of Body Type", title = "Make vs Body Type") +
  theme(plot.title = element_text(size = 18),axis.text.x = element_text(angle = 65,  hjust = 1),legend.key.size = unit(0.2,'cm'),legend.text = element_text(size = 5), legend.title = element_text(size = 5),
        legend.box = "vertical")
ggplotly(plotinter)

end_time <- Sys.time()
mem_end <- mem_used()
cpu_time <- end_time - start_time
mem_used_chunk <- mem_end - mem_start
cat("CPU time usage of code chunk:",cpu_time,"\n")
cat("Memory usage of code chunk:", mem_used_chunk/1048576, "MB\n")
```


```{r}
#ML model TEST TRAIN SPLIT
mem_start <- mem_used()
start_time <- Sys.time()

X<-car_training2[,1:12]
Y<-car_training2[,13]
set.seed(42)
splitIndex <- createDataPartition(Y, p = 0.7, list = FALSE, times = 1)
x_train <- X[splitIndex, ]
x_test <- X[-splitIndex, ]
y_train <- Y[splitIndex]
y_test <- Y[-splitIndex]

end_time <- Sys.time()
mem_end <- mem_used()
cpu_time <- end_time - start_time
mem_used_chunk <- mem_end - mem_start
cat("CPU time usage of code chunk:",cpu_time,"\n")
cat("Memory usage of code chunk:", mem_used_chunk/1048576, "MB\n")

```



```{r}
#ML Linear Regression Training and testing

start_time <- Sys.time()
mem_start <- mem_used()

lm_model <- train(x_train, y_train, method = "lm")
y_pred <- predict(lm_model, x_test)
#accuracy <- cor(y_pred, y_test)^2
#print(accuracy)
# end timer

# Get final memory usage
mem_end <- mem_used()

end_time <- Sys.time()

# calculate CPU time difference
cpu_time <- end_time - start_time
# Calculate memory usage of code chunk
mem_used_chunk <- mem_end - mem_start
# print CPU time
cat("CPU time usage of code chunk:",cpu_time,"\n")
cat("Memory usage of code chunk:", mem_used_chunk/1048576, "MB\n")
#Calculating metrics
mse <- mean((y_pred - y_test)^2)
mae <- mean(abs(y_pred - y_test))
rmse <- sqrt(mse)

print(paste("Linear Regression MSE: ", mse))
print(paste("Linear Regression MAE: ", mae))
print(paste("Linear Regression RMSE: ", rmse))
```

```{r}
saveRDS(lm_model, "LinearReg.rds")
file_info <- file.info("LinearReg.rds")
file_size <- file_info$size
print(file_size)

```

```{r}
# KNN Model
start_time <- Sys.time()
mem_start <- mem_used()

knnmodel = knnreg(x_train, y_train)

y_pred <- predict(knnmodel,x_test)

# Get final memory usage
mem_end <- mem_used()
end_time <- Sys.time()

cpu_time <- end_time - start_time
mem_used_chunk <- mem_end - mem_start
cat("CPU time usage of code chunk:",cpu_time,"\n")
cat("Memory usage of code chunk:", mem_used_chunk/1048576, "MB\n")

#Calculating metrics
mse <- mean((y_pred - y_test)^2)
mae <- mean(abs(y_pred - y_test))
rmse <- sqrt(mse)

print(paste("KNN MSE: ", mse))
print(paste("KNN MAE: ", mae))
print(paste("KNN RMSE: ", rmse))

```


```{r}
#Random Forest
# start timer
start_time <- Sys.time()
mem_start <- mem_used()


# Fit the random forest regression model using X_train and y_train
rf_model <- train(x_train, y_train,method="rf")# Use the model to predict on X_test
rfy_pred <- predict(rf_model, x_test)# Evaluate the model performance
rfrmse <- sqrt(mean((y_test - rfy_pred)^2))
rfr_squared <- cor(y_test, rfy_pred)^2# Print the model performance metrics
cat("Random Forest Regression Model\n")
cat("RMSE: ", rfrmse, "\n")
cat("R-squared: ", rfr_squared, "\n")

mem_end <- mem_used()
end_time <- Sys.time()


cpu_time <- end_time - start_time
mem_used_chunk <- mem_end - mem_start

cat("CPU time usage of code chunk:",cpu_time,"\n")
cat("Memory usage of code chunk:", mem_used_chunk/1048576, "MB\n")
```